# Aggregation


In [2]:
import numpy as np

np.random.seed(23) # seeding random generator to follow / give same array every time instead of random values
n64 = np.random.randint(low=1, high=20, size=(6,4))

print(n64)
print(np.sum(n64))
print(np.sum(n64, axis=0)) # this will add columns and gives 1D array
print(np.sum(n64, axis=1)) # this will give 1D array by adding rows into one element 

[[ 7  9 10  9]
 [14 13  8  7]
 [14 13 18  3]
 [12  6  1 13]
 [17 10 16  2]
 [ 8 16  5  2]]
233
[72 67 58 36]
[35 42 48 32 45 31]


In [3]:
np.random.seed(23)
n89 = np.random.randint(low=10, high=100, size=(8,9))
n89

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])

In [4]:
print(np.vsplit(n89, 2)) # split array into two eqaul sizes vertically
print(np.hsplit(n89, 3)) # vice versa horizontally

[array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96]]), array([[93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])]
[array([[93, 50, 83],
       [16, 55, 22],
       [22, 31, 58],
       [69, 49, 25],
       [93, 68, 35],
       [32, 48, 41],
       [24, 41, 88],
       [65, 37, 72]]), array([[64, 41, 86],
       [59, 76, 85],
       [51, 89, 72],
       [46, 75, 11],
       [76, 84, 45],
       [88, 10, 31],
       [93, 90, 80],
       [53, 84, 81]]), array([[49, 35, 61],
       [95, 79, 74],
       [67, 29, 43],
       [53, 25, 96],
       [66, 23, 70],
       [16, 42, 42],
       [76, 92, 95],
       [52, 93, 31]])]


In [5]:
# splitting the array using indices
print(np.vsplit(n89, [3,5,7])) # 0:3:5:7 vertical slicing
print(np.hsplit(n89, [2,4,5,7])) # 0:2:4:5:7 horizontal slicing

[array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43]]), array([[69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70]]), array([[32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95]]), array([[65, 37, 72, 53, 84, 81, 52, 93, 31]])]
[array([[93, 50],
       [16, 55],
       [22, 31],
       [69, 49],
       [93, 68],
       [32, 48],
       [24, 41],
       [65, 37]]), array([[83, 64],
       [22, 59],
       [58, 51],
       [25, 46],
       [35, 76],
       [41, 88],
       [88, 93],
       [72, 53]]), array([[41],
       [76],
       [89],
       [75],
       [84],
       [10],
       [90],
       [84]]), array([[86, 49],
       [85, 95],
       [72, 67],
       [11, 53],
       [45, 66],
       [31, 16],
       [80, 76],
       [81, 52]]), array([[35, 61],
       [79, 74],
       [29, 43],
       [25, 96],
       [23, 70],
       [42, 42],
       [

## Concat / Stack


In [6]:
n34 = np.arange(12).reshape(3,4)
n36 = np.arange(100, 118).reshape(3,6)
n64 = np.arange(200, 224).reshape(6,4)

print(np.concatenate((n34, n64), axis=0).shape) # This will add two arrays vertically if they have same size of columns
# this can be achived with np.vstack(n34,n64)
print(np.concatenate((n34, n36), axis=1).shape)  # This will add two arrays vertically if they have same size of rows
# this can be achived with np.hstack(n34, n36)

(9, 4)
(3, 10)


# Pandas


In [7]:
import os

os.getcwd()

'c:\\Users\\lokesh\\Documents\\Python Scripts'

In [8]:
import pandas as pd
import pandas_datareader as pdr

vlist = [100, 200,300,400]
labels = ["tata", "Brila", "Wipro", "Infy"]

ps1 = pd.Series(vlist, index=labels)
ps1



tata     100
Brila    200
Wipro    300
Infy     400
dtype: int64

In [9]:
md1 = {"tata":     100, 
"Brila":    200, # type: ignore
"Wipro":    300,
"Infy":     400}

ps2 = pd.Series(md1)
print(ps2.index)
print(ps2.values)
ps2

Index(['tata', 'Brila', 'Wipro', 'Infy'], dtype='object')
[100 200 300 400]


tata     100
Brila    200
Wipro    300
Infy     400
dtype: int64

##  DataFrame

####          Rev  Exp  HQ
##### Tata    100  50  'Mum'

In [10]:
row_labels = ["tata", "Brila", "Wipro", "Infy", "MRF", "TCS", "CapGmn", "CTS"]
col_label = ["Rev", "Exp", "HQ"]

values_list = [[100, 50, "Mum"], [200, 150, 'Kol'], [300, 250, "Blr"], [400, 350, 'Blr'], [500, 450, "Che"], [100, 50, "Mum"], [200, 150, 'Kol'], [300, 250, "Blr"]]

df1 = pd.DataFrame(values_list, index=row_labels, columns=col_label)

df1

Rev  Exp   HQ
tata    100   50  Mum
Brila   200  150  Kol
Wipro   300  250  Blr
Infy    400  350  Blr
MRF     500  450  Che
TCS     100   50  Mum
CapGmn  200  150  Kol
CTS     300  250  Blr

In [11]:
df1.tail()

Rev  Exp   HQ
Infy    400  350  Blr
MRF     500  450  Che
TCS     100   50  Mum
CapGmn  200  150  Kol
CTS     300  250  Blr

In [12]:
md2 = { "Rev": list(range(100, 500, 100)), "Exp": list(range(100, 600, 150)), "HQ": ["Blr", "Che", "Kol", "Mum"]}
df2 = pd.DataFrame(md2, index=row_labels[:4])

print(df2.shape)
print(df2.columns)
print(df2.index)
print(df2.ndim)
df2

(4, 3)
Index(['Rev', 'Exp', 'HQ'], dtype='object')
Index(['tata', 'Brila', 'Wipro', 'Infy'], dtype='object')
2


Rev  Exp   HQ
tata   100  100  Blr
Brila  200  250  Che
Wipro  300  400  Kol
Infy   400  550  Mum

In [16]:
df = pd.read_csv("lds_files\lds0.csv")
df

Vol     Rev  Exp Sector   EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt      NaN  Hyd    1    SPRT   
Kolkata_FMCG         925     NaN  676    NaN   1379.0  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    NaN   1935.0  NCR    0    NCRL   
Bangalore_Systems    900     NaN  650    Gov   1361.0  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub   1656.0  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov  13023.0  NCR    0    INDI   
Bangalore_Breweries  966     NaN  895    NaN    119.0  Blr    1    BREW   
Bombay_Finance       899     NaN  674    Pub      NaN  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    NaN   1154.0  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt   1873.0  NaN    1    EEST   

                          GST   Started  
Deccan_Sporting      Services  Mar 1943  
Kolkata_FMCG            Goods  Jan 1920  
NCR_Leagles          Services  Feb 1960  
Bangalore_Systems    Services  Apr 1950  
Chennai_Chemicals       Goods  Aug 1928  
Indi_Services        Services  Mar 1920  
Bangalore_Breweries     Goods  Oct 1971  
Bombay_Finance       Services  Apr 1925  
Chennai_Shipping        Goods  Nov 1930  
Eastern_Estates         Goods  Jan 1994

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Deccan_Sporting to Eastern_Estates
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Vol      10 non-null     int64  
 1   Rev      6 non-null      float64
 2   Exp      10 non-null     int64  
 3   Sector   6 non-null      object 
 4   EmpCnt   8 non-null      float64
 5   HQ       9 non-null      object 
 6   MNC      10 non-null     int64  
 7   StockID  10 non-null     object 
 8   GST      10 non-null     object 
 9   Started  10 non-null     object 
dtypes: float64(2), int64(3), object(5)
memory usage: 1.2+ KB


In [21]:
df.describe()

Vol         Rev         Exp        EmpCnt        MNC
count   10.000000    6.000000   10.000000      8.000000  10.000000
mean   940.900000  825.788333  678.600000   2812.500000   0.500000
std     29.696427   48.418992   93.890243   4164.678139   0.527046
min    899.000000  733.000000  605.000000    119.000000   0.000000
25%    926.500000  824.307500  610.500000   1309.250000   0.000000
50%    938.000000  837.015000  657.500000   1517.500000   0.500000
75%    963.000000  857.350000  675.500000   1888.500000   1.000000
max    992.000000  863.500000  895.000000  13023.000000   1.000000

In [23]:
df.describe(include='all')

Vol         Rev         Exp Sector        EmpCnt   HQ  \
count    10.000000    6.000000   10.000000      6      8.000000    9   
unique         NaN         NaN         NaN      3           NaN    6   
top            NaN         NaN         NaN    Pvt           NaN  NCR   
freq           NaN         NaN         NaN      2           NaN    2   
mean    940.900000  825.788333  678.600000    NaN   2812.500000  NaN   
std      29.696427   48.418992   93.890243    NaN   4164.678139  NaN   
min     899.000000  733.000000  605.000000    NaN    119.000000  NaN   
25%     926.500000  824.307500  610.500000    NaN   1309.250000  NaN   
50%     938.000000  837.015000  657.500000    NaN   1517.500000  NaN   
75%     963.000000  857.350000  675.500000    NaN   1888.500000  NaN   
max     992.000000  863.500000  895.000000    NaN  13023.000000  NaN   

              MNC StockID       GST   Started  
count   10.000000      10        10        10  
unique        NaN      10         2        10  
top           NaN    SPRT  Services  Mar 1943  
freq          NaN       1         5         1  
mean     0.500000     NaN       NaN       NaN  
std      0.527046     NaN       NaN       NaN  
min      0.000000     NaN       NaN       NaN  
25%      0.000000     NaN       NaN       NaN  
50%      0.500000     NaN       NaN       NaN  
75%      1.000000     NaN       NaN       NaN  
max      1.000000     NaN       NaN       NaN

In [24]:
df.describe(include=np.int64)

Vol         Exp        MNC
count   10.000000   10.000000  10.000000
mean   940.900000  678.600000   0.500000
std     29.696427   93.890243   0.527046
min    899.000000  605.000000   0.000000
25%    926.500000  610.500000   0.000000
50%    938.000000  657.500000   0.500000
75%    963.000000  675.500000   1.000000
max    992.000000  895.000000   1.000000

In [25]:
df.Vol

Deccan_Sporting        931
Kolkata_FMCG           925
NCR_Leagles            931
Bangalore_Systems      900
Chennai_Chemicals      966
Indi_Services          954
Bangalore_Breweries    966
Bombay_Finance         899
Chennai_Shipping       992
Eastern_Estates        945
Name: Vol, dtype: int64

In [36]:
df.iloc[4, 4]
print(df.iloc[0:5:2, 1:8:3]) # slicing with indecies
df


                     Rev  EmpCnt StockID
Deccan_Sporting    839.8     NaN    SPRT
NCR_Leagles        863.5  1935.0    NCRL
Chennai_Chemicals  863.2  1656.0    CHEM


Vol     Rev  Exp Sector   EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt      NaN  Hyd    1    SPRT   
Kolkata_FMCG         925     NaN  676    NaN   1379.0  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    NaN   1935.0  NCR    0    NCRL   
Bangalore_Systems    900     NaN  650    Gov   1361.0  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub   1656.0  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov  13023.0  NCR    0    INDI   
Bangalore_Breweries  966     NaN  895    NaN    119.0  Blr    1    BREW   
Bombay_Finance       899     NaN  674    Pub      NaN  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    NaN   1154.0  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt   1873.0  NaN    1    EEST   

                          GST   Started  
Deccan_Sporting      Services  Mar 1943  
Kolkata_FMCG            Goods  Jan 1920  
NCR_Leagles          Services  Feb 1960  
Bangalore_Systems    Services  Apr 1950  
Chennai_Chemicals       Goods  Aug 1928  
Indi_Services        Services  Mar 1920  
Bangalore_Breweries     Goods  Oct 1971  
Bombay_Finance       Services  Apr 1925  
Chennai_Shipping        Goods  Nov 1930  
Eastern_Estates         Goods  Jan 1994

In [38]:
print(df.iloc[[0,2,-2,-1], [0,1,-3,-2,-1]]) # slicing with indecies
df

                  Vol     Rev StockID       GST   Started
Deccan_Sporting   931  839.80    SPRT  Services  Mar 1943
NCR_Leagles       931  863.50    NCRL  Services  Feb 1960
Chennai_Shipping  992  821.00    SHIP     Goods  Nov 1930
Eastern_Estates   945  834.23    EEST     Goods  Jan 1994


Vol     Rev  Exp Sector   EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt      NaN  Hyd    1    SPRT   
Kolkata_FMCG         925     NaN  676    NaN   1379.0  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    NaN   1935.0  NCR    0    NCRL   
Bangalore_Systems    900     NaN  650    Gov   1361.0  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub   1656.0  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov  13023.0  NCR    0    INDI   
Bangalore_Breweries  966     NaN  895    NaN    119.0  Blr    1    BREW   
Bombay_Finance       899     NaN  674    Pub      NaN  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    NaN   1154.0  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt   1873.0  NaN    1    EEST   

                          GST   Started  
Deccan_Sporting      Services  Mar 1943  
Kolkata_FMCG            Goods  Jan 1920  
NCR_Leagles          Services  Feb 1960  
Bangalore_Systems    Services  Apr 1950  
Chennai_Chemicals       Goods  Aug 1928  
Indi_Services        Services  Mar 1920  
Bangalore_Breweries     Goods  Oct 1971  
Bombay_Finance       Services  Apr 1925  
Chennai_Shipping        Goods  Nov 1930  
Eastern_Estates         Goods  Jan 1994

In [39]:
print(df.columns)
df.loc["Indi_Services"]

Index(['Vol', 'Rev', 'Exp', 'Sector', 'EmpCnt', 'HQ', 'MNC', 'StockID', 'GST',
       'Started'],
      dtype='object')


Vol             954
Rev           733.0
Exp             609
Sector          Gov
EmpCnt      13023.0
HQ              NCR
MNC               0
StockID        INDI
GST        Services
Started    Mar 1920
Name: Indi_Services, dtype: object

In [41]:
df.loc["Indi_Services", "Rev"]

733.0

In [44]:
df.loc["Indi_Services":"Chennai_Shipping":2]

Vol    Rev  Exp Sector   EmpCnt   HQ  MNC StockID       GST  \
Indi_Services   954  733.0  609    Gov  13023.0  NCR    0    INDI  Services   
Bombay_Finance  899    NaN  674    Pub      NaN  Mum    0    BFIN  Services   

                 Started  
Indi_Services   Mar 1920  
Bombay_Finance  Apr 1925

### Sector Access


In [46]:
sector_mask1 = df.Sector == "Pub"
df[sector_mask1]

Vol    Rev  Exp Sector  EmpCnt   HQ  MNC StockID       GST  \
Chennai_Chemicals  966  863.2  608    Pub  1656.0  Che    1    CHEM     Goods   
Bombay_Finance     899    NaN  674    Pub     NaN  Mum    0    BFIN  Services   

                    Started  
Chennai_Chemicals  Aug 1928  
Bombay_Finance     Apr 1925