# Aggregation


In [2]:
import numpy as np

np.random.seed(23) # seeding random generator to follow / give same array every time instead of random values
n64 = np.random.randint(low=1, high=20, size=(6,4))

print(n64)
print(np.sum(n64))
print(np.sum(n64, axis=0)) # this will add columns and gives 1D array
print(np.sum(n64, axis=1)) # this will give 1D array by adding rows into one element 

[[ 7  9 10  9]
 [14 13  8  7]
 [14 13 18  3]
 [12  6  1 13]
 [17 10 16  2]
 [ 8 16  5  2]]
233
[72 67 58 36]
[35 42 48 32 45 31]


In [3]:
np.random.seed(23)
n89 = np.random.randint(low=10, high=100, size=(8,9))
n89

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])

In [4]:
print(np.vsplit(n89, 2)) # split array into two eqaul sizes vertically
print(np.hsplit(n89, 3)) # vice versa horizontally

[array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96]]), array([[93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95],
       [65, 37, 72, 53, 84, 81, 52, 93, 31]])]
[array([[93, 50, 83],
       [16, 55, 22],
       [22, 31, 58],
       [69, 49, 25],
       [93, 68, 35],
       [32, 48, 41],
       [24, 41, 88],
       [65, 37, 72]]), array([[64, 41, 86],
       [59, 76, 85],
       [51, 89, 72],
       [46, 75, 11],
       [76, 84, 45],
       [88, 10, 31],
       [93, 90, 80],
       [53, 84, 81]]), array([[49, 35, 61],
       [95, 79, 74],
       [67, 29, 43],
       [53, 25, 96],
       [66, 23, 70],
       [16, 42, 42],
       [76, 92, 95],
       [52, 93, 31]])]


In [5]:
# splitting the array using indices
print(np.vsplit(n89, [3,5,7])) # 0:3:5:7 vertical slicing
print(np.hsplit(n89, [2,4,5,7])) # 0:2:4:5:7 horizontal slicing

[array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43]]), array([[69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70]]), array([[32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95]]), array([[65, 37, 72, 53, 84, 81, 52, 93, 31]])]
[array([[93, 50],
       [16, 55],
       [22, 31],
       [69, 49],
       [93, 68],
       [32, 48],
       [24, 41],
       [65, 37]]), array([[83, 64],
       [22, 59],
       [58, 51],
       [25, 46],
       [35, 76],
       [41, 88],
       [88, 93],
       [72, 53]]), array([[41],
       [76],
       [89],
       [75],
       [84],
       [10],
       [90],
       [84]]), array([[86, 49],
       [85, 95],
       [72, 67],
       [11, 53],
       [45, 66],
       [31, 16],
       [80, 76],
       [81, 52]]), array([[35, 61],
       [79, 74],
       [29, 43],
       [25, 96],
       [23, 70],
       [42, 42],
       [

## Concat / Stack


In [6]:
n34 = np.arange(12).reshape(3,4)
n36 = np.arange(100, 118).reshape(3,6)
n64 = np.arange(200, 224).reshape(6,4)

print(np.concatenate((n34, n64), axis=0).shape) # This will add two arrays vertically if they have same size of columns
# this can be achived with np.vstack(n34,n64)
print(np.concatenate((n34, n36), axis=1).shape)  # This will add two arrays vertically if they have same size of rows
# this can be achived with np.hstack(n34, n36)

(9, 4)
(3, 10)


# Pandas


In [7]:
import os

os.getcwd()

'c:\\Users\\lokesh\\Documents\\Python Scripts'

In [8]:
import pandas as pd
import pandas_datareader as pdr

vlist = [100, 200,300,400]
labels = ["tata", "Brila", "Wipro", "Infy"]

ps1 = pd.Series(vlist, index=labels)
ps1



tata     100
Brila    200
Wipro    300
Infy     400
dtype: int64

In [9]:
md1 = {"tata":     100, 
"Brila":    200, # type: ignore
"Wipro":    300,
"Infy":     400}

ps2 = pd.Series(md1)
print(ps2.index)
print(ps2.values)
ps2

Index(['tata', 'Brila', 'Wipro', 'Infy'], dtype='object')
[100 200 300 400]


tata     100
Brila    200
Wipro    300
Infy     400
dtype: int64

##  DataFrame

####          Rev  Exp  HQ
##### Tata    100  50  'Mum'

In [10]:
row_labels = ["tata", "Brila", "Wipro", "Infy", "MRF", "TCS", "CapGmn", "CTS"]
col_label = ["Rev", "Exp", "HQ"]

values_list = [[100, 50, "Mum"], [200, 150, 'Kol'], [300, 250, "Blr"], [400, 350, 'Blr'], [500, 450, "Che"], [100, 50, "Mum"], [200, 150, 'Kol'], [300, 250, "Blr"]]

df1 = pd.DataFrame(values_list, index=row_labels, columns=col_label)

df1

Rev  Exp   HQ
tata    100   50  Mum
Brila   200  150  Kol
Wipro   300  250  Blr
Infy    400  350  Blr
MRF     500  450  Che
TCS     100   50  Mum
CapGmn  200  150  Kol
CTS     300  250  Blr

In [11]:
df1.tail()

Rev  Exp   HQ
Infy    400  350  Blr
MRF     500  450  Che
TCS     100   50  Mum
CapGmn  200  150  Kol
CTS     300  250  Blr

In [12]:
md2 = { "Rev": list(range(100, 500, 100)), "Exp": list(range(100, 600, 150)), "HQ": ["Blr", "Che", "Kol", "Mum"]}
df2 = pd.DataFrame(md2, index=row_labels[:4])

print(df2.shape)
print(df2.columns)
print(df2.index)
print(df2.ndim)
df2

(4, 3)
Index(['Rev', 'Exp', 'HQ'], dtype='object')
Index(['tata', 'Brila', 'Wipro', 'Infy'], dtype='object')
2


Rev  Exp   HQ
tata   100  100  Blr
Brila  200  250  Che
Wipro  300  400  Kol
Infy   400  550  Mum

In [16]:
df = pd.read_csv("lds_files\lds0.csv")
df

Vol     Rev  Exp Sector   EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt      NaN  Hyd    1    SPRT   
Kolkata_FMCG         925     NaN  676    NaN   1379.0  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    NaN   1935.0  NCR    0    NCRL   
Bangalore_Systems    900     NaN  650    Gov   1361.0  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub   1656.0  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov  13023.0  NCR    0    INDI   
Bangalore_Breweries  966     NaN  895    NaN    119.0  Blr    1    BREW   
Bombay_Finance       899     NaN  674    Pub      NaN  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    NaN   1154.0  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt   1873.0  NaN    1    EEST   

                          GST   Started  
Deccan_Sporting      Services  Mar 1943  
Kolkata_FMCG            Goods  Jan 1920  
NCR_Leagles          Services  Feb 1960  
Bangalore_Systems    Services  Apr 1950  
Chennai_Chemicals       Goods  Aug 1928  
Indi_Services        Services  Mar 1920  
Bangalore_Breweries     Goods  Oct 1971  
Bombay_Finance       Services  Apr 1925  
Chennai_Shipping        Goods  Nov 1930  
Eastern_Estates         Goods  Jan 1994

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Deccan_Sporting to Eastern_Estates
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Vol      10 non-null     int64  
 1   Rev      6 non-null      float64
 2   Exp      10 non-null     int64  
 3   Sector   6 non-null      object 
 4   EmpCnt   8 non-null      float64
 5   HQ       9 non-null      object 
 6   MNC      10 non-null     int64  
 7   StockID  10 non-null     object 
 8   GST      10 non-null     object 
 9   Started  10 non-null     object 
dtypes: float64(2), int64(3), object(5)
memory usage: 1.2+ KB


In [21]:
df.describe()

Vol         Rev         Exp        EmpCnt        MNC
count   10.000000    6.000000   10.000000      8.000000  10.000000
mean   940.900000  825.788333  678.600000   2812.500000   0.500000
std     29.696427   48.418992   93.890243   4164.678139   0.527046
min    899.000000  733.000000  605.000000    119.000000   0.000000
25%    926.500000  824.307500  610.500000   1309.250000   0.000000
50%    938.000000  837.015000  657.500000   1517.500000   0.500000
75%    963.000000  857.350000  675.500000   1888.500000   1.000000
max    992.000000  863.500000  895.000000  13023.000000   1.000000

In [23]:
df.describe(include='all')

Vol         Rev         Exp Sector        EmpCnt   HQ  \
count    10.000000    6.000000   10.000000      6      8.000000    9   
unique         NaN         NaN         NaN      3           NaN    6   
top            NaN         NaN         NaN    Pvt           NaN  NCR   
freq           NaN         NaN         NaN      2           NaN    2   
mean    940.900000  825.788333  678.600000    NaN   2812.500000  NaN   
std      29.696427   48.418992   93.890243    NaN   4164.678139  NaN   
min     899.000000  733.000000  605.000000    NaN    119.000000  NaN   
25%     926.500000  824.307500  610.500000    NaN   1309.250000  NaN   
50%     938.000000  837.015000  657.500000    NaN   1517.500000  NaN   
75%     963.000000  857.350000  675.500000    NaN   1888.500000  NaN   
max     992.000000  863.500000  895.000000    NaN  13023.000000  NaN   

              MNC StockID       GST   Started  
count   10.000000      10        10        10  
unique        NaN      10         2        10  
top           NaN    SPRT  Services  Mar 1943  
freq          NaN       1         5         1  
mean     0.500000     NaN       NaN       NaN  
std      0.527046     NaN       NaN       NaN  
min      0.000000     NaN       NaN       NaN  
25%      0.000000     NaN       NaN       NaN  
50%      0.500000     NaN       NaN       NaN  
75%      1.000000     NaN       NaN       NaN  
max      1.000000     NaN       NaN       NaN

In [24]:
df.describe(include=np.int64)

Vol         Exp        MNC
count   10.000000   10.000000  10.000000
mean   940.900000  678.600000   0.500000
std     29.696427   93.890243   0.527046
min    899.000000  605.000000   0.000000
25%    926.500000  610.500000   0.000000
50%    938.000000  657.500000   0.500000
75%    963.000000  675.500000   1.000000
max    992.000000  895.000000   1.000000

In [25]:
df.Vol

Deccan_Sporting        931
Kolkata_FMCG           925
NCR_Leagles            931
Bangalore_Systems      900
Chennai_Chemicals      966
Indi_Services          954
Bangalore_Breweries    966
Bombay_Finance         899
Chennai_Shipping       992
Eastern_Estates        945
Name: Vol, dtype: int64

In [36]:
df.iloc[4, 4]
print(df.iloc[0:5:2, 1:8:3]) # slicing with indecies
df


                     Rev  EmpCnt StockID
Deccan_Sporting    839.8     NaN    SPRT
NCR_Leagles        863.5  1935.0    NCRL
Chennai_Chemicals  863.2  1656.0    CHEM


Vol     Rev  Exp Sector   EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt      NaN  Hyd    1    SPRT   
Kolkata_FMCG         925     NaN  676    NaN   1379.0  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    NaN   1935.0  NCR    0    NCRL   
Bangalore_Systems    900     NaN  650    Gov   1361.0  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub   1656.0  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov  13023.0  NCR    0    INDI   
Bangalore_Breweries  966     NaN  895    NaN    119.0  Blr    1    BREW   
Bombay_Finance       899     NaN  674    Pub      NaN  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    NaN   1154.0  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt   1873.0  NaN    1    EEST   

                          GST   Started  
Deccan_Sporting      Services  Mar 1943  
Kolkata_FMCG            Goods  Jan 1920  
NCR_Leagles          Services  Feb 1960  
Bangalore_Systems    Services  Apr 1950  
Chennai_Chemicals       Goods  Aug 1928  
Indi_Services        Services  Mar 1920  
Bangalore_Breweries     Goods  Oct 1971  
Bombay_Finance       Services  Apr 1925  
Chennai_Shipping        Goods  Nov 1930  
Eastern_Estates         Goods  Jan 1994

In [38]:
print(df.iloc[[0,2,-2,-1], [0,1,-3,-2,-1]]) # slicing with indecies
df

                  Vol     Rev StockID       GST   Started
Deccan_Sporting   931  839.80    SPRT  Services  Mar 1943
NCR_Leagles       931  863.50    NCRL  Services  Feb 1960
Chennai_Shipping  992  821.00    SHIP     Goods  Nov 1930
Eastern_Estates   945  834.23    EEST     Goods  Jan 1994


Vol     Rev  Exp Sector   EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt      NaN  Hyd    1    SPRT   
Kolkata_FMCG         925     NaN  676    NaN   1379.0  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    NaN   1935.0  NCR    0    NCRL   
Bangalore_Systems    900     NaN  650    Gov   1361.0  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub   1656.0  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov  13023.0  NCR    0    INDI   
Bangalore_Breweries  966     NaN  895    NaN    119.0  Blr    1    BREW   
Bombay_Finance       899     NaN  674    Pub      NaN  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    NaN   1154.0  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt   1873.0  NaN    1    EEST   

                          GST   Started  
Deccan_Sporting      Services  Mar 1943  
Kolkata_FMCG            Goods  Jan 1920  
NCR_Leagles          Services  Feb 1960  
Bangalore_Systems    Services  Apr 1950  
Chennai_Chemicals       Goods  Aug 1928  
Indi_Services        Services  Mar 1920  
Bangalore_Breweries     Goods  Oct 1971  
Bombay_Finance       Services  Apr 1925  
Chennai_Shipping        Goods  Nov 1930  
Eastern_Estates         Goods  Jan 1994

In [39]:
print(df.columns)
df.loc["Indi_Services"]

Index(['Vol', 'Rev', 'Exp', 'Sector', 'EmpCnt', 'HQ', 'MNC', 'StockID', 'GST',
       'Started'],
      dtype='object')


Vol             954
Rev           733.0
Exp             609
Sector          Gov
EmpCnt      13023.0
HQ              NCR
MNC               0
StockID        INDI
GST        Services
Started    Mar 1920
Name: Indi_Services, dtype: object

In [41]:
df.loc["Indi_Services", "Rev"]

733.0

In [44]:
df.loc["Indi_Services":"Chennai_Shipping":2]

Vol    Rev  Exp Sector   EmpCnt   HQ  MNC StockID       GST  \
Indi_Services   954  733.0  609    Gov  13023.0  NCR    0    INDI  Services   
Bombay_Finance  899    NaN  674    Pub      NaN  Mum    0    BFIN  Services   

                 Started  
Indi_Services   Mar 1920  
Bombay_Finance  Apr 1925

### Sector Access


In [49]:
sector_mask1 = (df.Sector == "Pub") & (df.GST == "Services")
df[sector_mask1]

Vol  Rev  Exp Sector  EmpCnt   HQ  MNC StockID       GST  \
Bombay_Finance  899  NaN  674    Pub     NaN  Mum    0    BFIN  Services   

                 Started  
Bombay_Finance  Apr 1925

In [51]:
df[df.Rev >= df.Rev.mean()].EmpCnt

Deccan_Sporting         NaN
NCR_Leagles          1935.0
Chennai_Chemicals    1656.0
Eastern_Estates      1873.0
Name: EmpCnt, dtype: float64

In [53]:
df.loc[df.Rev >= df.Rev.mean(), ["EmpCnt", 'HQ']]

EmpCnt   HQ
Deccan_Sporting       NaN  Hyd
NCR_Leagles        1935.0  NCR
Chennai_Chemicals  1656.0  Che
Eastern_Estates    1873.0  NaN

### Feature Scaling and Mutability

In [56]:
df["Profit"] = df.Rev - df.Exp
df

Vol     Rev  Exp Sector   EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt      NaN  Hyd    1    SPRT   
Kolkata_FMCG         925     NaN  676    NaN   1379.0  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    NaN   1935.0  NCR    0    NCRL   
Bangalore_Systems    900     NaN  650    Gov   1361.0  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub   1656.0  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov  13023.0  NCR    0    INDI   
Bangalore_Breweries  966     NaN  895    NaN    119.0  Blr    1    BREW   
Bombay_Finance       899     NaN  674    Pub      NaN  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    NaN   1154.0  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt   1873.0  NaN    1    EEST   

                          GST   Started  Profit  
Deccan_Sporting      Services  Mar 1943  224.80  
Kolkata_FMCG            Goods  Jan 1920     NaN  
NCR_Leagles          Services  Feb 1960  258.50  
Bangalore_Systems    Services  Apr 1950     NaN  
Chennai_Chemicals       Goods  Aug 1928  255.20  
Indi_Services        Services  Mar 1920  124.00  
Bangalore_Breweries     Goods  Oct 1971     NaN  
Bombay_Finance       Services  Apr 1925     NaN  
Chennai_Shipping        Goods  Nov 1930  156.00  
Eastern_Estates         Goods  Jan 1994   45.23

In [59]:
df.loc[df.Rev >= df.Rev.mean(), "Rev"]=999
df

Vol    Rev  Exp Sector   EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  999.0  615    Pvt      NaN  Hyd    1    SPRT   
Kolkata_FMCG         925    NaN  676    NaN   1379.0  Kol    0    KFMC   
NCR_Leagles          931  999.0  605    NaN   1935.0  NCR    0    NCRL   
Bangalore_Systems    900    NaN  650    Gov   1361.0  Blr    0    BSYS   
Chennai_Chemicals    966  999.0  608    Pub   1656.0  Che    1    CHEM   
Indi_Services        954  733.0  609    Gov  13023.0  NCR    0    INDI   
Bangalore_Breweries  966    NaN  895    NaN    119.0  Blr    1    BREW   
Bombay_Finance       899    NaN  674    Pub      NaN  Mum    0    BFIN   
Chennai_Shipping     992  821.0  665    NaN   1154.0  Che    1    SHIP   
Eastern_Estates      945  999.0  789    Pvt   1873.0  NaN    1    EEST   

                          GST   Started  Profit  
Deccan_Sporting      Services  Mar 1943  224.80  
Kolkata_FMCG            Goods  Jan 1920     NaN  
NCR_Leagles          Services  Feb 1960  258.50  
Bangalore_Systems    Services  Apr 1950     NaN  
Chennai_Chemicals       Goods  Aug 1928  255.20  
Indi_Services        Services  Mar 1920  124.00  
Bangalore_Breweries     Goods  Oct 1971     NaN  
Bombay_Finance       Services  Apr 1925     NaN  
Chennai_Shipping        Goods  Nov 1930  156.00  
Eastern_Estates         Goods  Jan 1994   45.23

In [68]:
# df.drop(columns=["Profit"])
df.insert(loc=3, column="Profit", value=df.Rev - df.Exp, allow_duplicates=True)
df

Vol    Rev  Exp  Profit  Profit Sector   EmpCnt   HQ  \
Deccan_Sporting      931  999.0  615   384.0   384.0    Pvt      NaN  Hyd   
Kolkata_FMCG         925    NaN  676     NaN     NaN    NaN   1379.0  Kol   
NCR_Leagles          931  999.0  605   394.0   394.0    NaN   1935.0  NCR   
Bangalore_Systems    900    NaN  650     NaN     NaN    Gov   1361.0  Blr   
Chennai_Chemicals    966  999.0  608   391.0   391.0    Pub   1656.0  Che   
Indi_Services        954  733.0  609   124.0   124.0    Gov  13023.0  NCR   
Bangalore_Breweries  966    NaN  895     NaN     NaN    NaN    119.0  Blr   
Bombay_Finance       899    NaN  674     NaN     NaN    Pub      NaN  Mum   
Chennai_Shipping     992  821.0  665   156.0   156.0    NaN   1154.0  Che   
Eastern_Estates      945  999.0  789   210.0   210.0    Pvt   1873.0  NaN   

                     MNC StockID       GST   Started  Profit  
Deccan_Sporting        1    SPRT  Services  Mar 1943  224.80  
Kolkata_FMCG           0    KFMC     Goods  Jan 1920     NaN  
NCR_Leagles            0    NCRL  Services  Feb 1960  258.50  
Bangalore_Systems      0    BSYS  Services  Apr 1950     NaN  
Chennai_Chemicals      1    CHEM     Goods  Aug 1928  255.20  
Indi_Services          0    INDI  Services  Mar 1920  124.00  
Bangalore_Breweries    1    BREW     Goods  Oct 1971     NaN  
Bombay_Finance         0    BFIN  Services  Apr 1925     NaN  
Chennai_Shipping       1    SHIP     Goods  Nov 1930  156.00  
Eastern_Estates        1    EEST     Goods  Jan 1994   45.23

# Sorting on DataFrame

In [25]:
import pandas as pd
df = pd.read_csv("lds_files\lds1.csv")
df

Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt     154  Hyd    1    SPRT   
Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL   
Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov   13023  NCR    0    INDI   
Bangalore_Breweries  966  805.00  899    Pvt     119  Blr    1    BREW   
Bombay_Finance       899  917.00  674    Pub    1443  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    Pub     899  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt    1873  Kol    1    EEST   
Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV   

                          GST Start Date  
Deccan_Sporting      Services   Mar 1943  
Kolkata_FMCG            Goods   Jan 1920  
NCR_Leagles          Services   Feb 1960  
Bangalore_Systems    Services   Apr 1950  
Chennai_Chemicals       Goods   Aug 1928  
Indi_Services        Services   Mar 1920  
Bangalore_Breweries     Goods   Oct 1971  
Bombay_Finance       Services   Apr 1925  
Chennai_Shipping        Goods   Nov 1930  
Eastern_Estates         Goods   Jan 1994  
Central_Services     Services   Jun 1974

In [71]:
df.sort_index() #msorts the Data by default with row lables as they are in the first column

Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Bangalore_Breweries  966  805.00  899    Pvt     119  Blr    1    BREW   
Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS   
Bombay_Finance       899  917.00  674    Pub    1443  Mum    0    BFIN   
Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV   
Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM   
Chennai_Shipping     992  821.00  665    Pub     899  Che    1    SHIP   
Deccan_Sporting      931  839.80  615    Pvt     154  Hyd    1    SPRT   
Eastern_Estates      945  834.23  789    Pvt    1873  Kol    1    EEST   
Indi_Services        954  733.00  609    Gov   13023  NCR    0    INDI   
Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL   

                          GST Start Date  
Bangalore_Breweries     Goods   Oct 1971  
Bangalore_Systems    Services   Apr 1950  
Bombay_Finance       Services   Apr 1925  
Central_Services     Services   Jun 1974  
Chennai_Chemicals       Goods   Aug 1928  
Chennai_Shipping        Goods   Nov 1930  
Deccan_Sporting      Services   Mar 1943  
Eastern_Estates         Goods   Jan 1994  
Indi_Services        Services   Mar 1920  
Kolkata_FMCG            Goods   Jan 1920  
NCR_Leagles          Services   Feb 1960

In [72]:
df.sort_index(axis=1)

EmpCnt  Exp       GST   HQ  MNC     Rev Sector  \
Deccan_Sporting         154  615  Services  Hyd    1  839.80    Pvt   
Kolkata_FMCG           1379  676     Goods  Kol    0  874.40    Pub   
NCR_Leagles            1935  605  Services  NCR    0  863.50    Pub   
Bangalore_Systems      1361  650  Services  Blr    0  881.60    Gov   
Chennai_Chemicals      1656  608     Goods  Che    1  863.20    Pub   
Indi_Services         13023  609  Services  NCR    0  733.00    Gov   
Bangalore_Breweries     119  899     Goods  Blr    1  805.00    Pvt   
Bombay_Finance         1443  674  Services  Mum    0  917.00    Pub   
Chennai_Shipping        899  665     Goods  Che    1  821.00    Pub   
Eastern_Estates        1873  789     Goods  Kol    1  834.23    Pvt   
Central_Services       1573  689  Services  NCR    1  824.00    Gov   

                    Start Date StockID  Vol  
Deccan_Sporting       Mar 1943    SPRT  931  
Kolkata_FMCG          Jan 1920    KFMC  925  
NCR_Leagles           Feb 1960    NCRL  931  
Bangalore_Systems     Apr 1950    BSYS  900  
Chennai_Chemicals     Aug 1928    CHEM  966  
Indi_Services         Mar 1920    INDI  954  
Bangalore_Breweries   Oct 1971    BREW  966  
Bombay_Finance        Apr 1925    BFIN  899  
Chennai_Shipping      Nov 1930    SHIP  992  
Eastern_Estates       Jan 1994    EEST  945  
Central_Services      Jun 1974    CSRV  934

In [75]:
df.sort_values(by="Rev", ascending=False)

Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Bombay_Finance       899  917.00  674    Pub    1443  Mum    0    BFIN   
Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS   
Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL   
Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM   
Deccan_Sporting      931  839.80  615    Pvt     154  Hyd    1    SPRT   
Eastern_Estates      945  834.23  789    Pvt    1873  Kol    1    EEST   
Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV   
Chennai_Shipping     992  821.00  665    Pub     899  Che    1    SHIP   
Bangalore_Breweries  966  805.00  899    Pvt     119  Blr    1    BREW   
Indi_Services        954  733.00  609    Gov   13023  NCR    0    INDI   

                          GST Start Date  
Bombay_Finance       Services   Apr 1925  
Bangalore_Systems    Services   Apr 1950  
Kolkata_FMCG            Goods   Jan 1920  
NCR_Leagles          Services   Feb 1960  
Chennai_Chemicals       Goods   Aug 1928  
Deccan_Sporting      Services   Mar 1943  
Eastern_Estates         Goods   Jan 1994  
Central_Services     Services   Jun 1974  
Chennai_Shipping        Goods   Nov 1930  
Bangalore_Breweries     Goods   Oct 1971  
Indi_Services        Services   Mar 1920

In [4]:
df.sort_values(by=["Rev", "Exp"], axis=0, ascending=[True, False])

Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Indi_Services        954  733.00  609    Gov   13023  NCR    0    INDI   
Bangalore_Breweries  966  805.00  899    Pvt     119  Blr    1    BREW   
Chennai_Shipping     992  821.00  665    Pub     899  Che    1    SHIP   
Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV   
Eastern_Estates      945  834.23  789    Pvt    1873  Kol    1    EEST   
Deccan_Sporting      931  839.80  615    Pvt     154  Hyd    1    SPRT   
Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM   
NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL   
Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC   
Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS   
Bombay_Finance       899  917.00  674    Pub    1443  Mum    0    BFIN   

                          GST Start Date  
Indi_Services        Services   Mar 1920  
Bangalore_Breweries     Goods   Oct 1971  
Chennai_Shipping        Goods   Nov 1930  
Central_Services     Services   Jun 1974  
Eastern_Estates         Goods   Jan 1994  
Deccan_Sporting      Services   Mar 1943  
Chennai_Chemicals       Goods   Aug 1928  
NCR_Leagles          Services   Feb 1960  
Kolkata_FMCG            Goods   Jan 1920  
Bangalore_Systems    Services   Apr 1950  
Bombay_Finance       Services   Apr 1925

In [5]:
df["Umrank"] = df.Vol.rank(axis=0, method="average", ascending=False)
df

Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt     154  Hyd    1    SPRT   
Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL   
Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov   13023  NCR    0    INDI   
Bangalore_Breweries  966  805.00  899    Pvt     119  Blr    1    BREW   
Bombay_Finance       899  917.00  674    Pub    1443  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    Pub     899  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt    1873  Kol    1    EEST   
Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV   

                          GST Start Date  Umrank  
Deccan_Sporting      Services   Mar 1943     7.5  
Kolkata_FMCG            Goods   Jan 1920     9.0  
NCR_Leagles          Services   Feb 1960     7.5  
Bangalore_Systems    Services   Apr 1950    10.0  
Chennai_Chemicals       Goods   Aug 1928     2.5  
Indi_Services        Services   Mar 1920     4.0  
Bangalore_Breweries     Goods   Oct 1971     2.5  
Bombay_Finance       Services   Apr 1925    11.0  
Chennai_Shipping        Goods   Nov 1930     1.0  
Eastern_Estates         Goods   Jan 1994     5.0  
Central_Services     Services   Jun 1974     6.0

In [26]:
df.to_csv("output/pandas/dataset.csv")
df.to_json("output/pandas/dataset.json")
df.to_excel("output/pandas/dataset.xlsx")
df.to_html("output/pandas/dataset.html")


In [18]:
pd.read_html("output/pandas/dataset.html", index_col=0)

[                     Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
 Deccan_Sporting      931  839.80  615    Pvt     154  Hyd    1    SPRT   
 Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC   
 NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL   
 Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS   
 Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM   
 Indi_Services        954  733.00  609    Gov   13023  NCR    0    INDI   
 Bangalore_Breweries  966  805.00  899    Pvt     119  Blr    1    BREW   
 Bombay_Finance       899  917.00  674    Pub    1443  Mum    0    BFIN   
 Chennai_Shipping     992  821.00  665    Pub     899  Che    1    SHIP   
 Eastern_Estates      945  834.23  789    Pvt    1873  Kol    1    EEST   
 Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV   
 
                           GST Start Date  Umrank  
 Deccan_Sporting      Services   Mar 1943     

# Mapping Data Frame with Dictionary values

In [19]:
md = { "Hyd": 'SZ', "Blr": "SZ", "Che": "SZ", "Mum": "WZ", "NCR": "NZ", "Kol": "EZ"}

df["Zone"] = df.HQ.map(md)

df

Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt     154  Hyd    1    SPRT   
Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL   
Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov   13023  NCR    0    INDI   
Bangalore_Breweries  966  805.00  899    Pvt     119  Blr    1    BREW   
Bombay_Finance       899  917.00  674    Pub    1443  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    Pub     899  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt    1873  Kol    1    EEST   
Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV   

                          GST Start Date  Umrank Zone  
Deccan_Sporting      Services   Mar 1943     7.5   SZ  
Kolkata_FMCG            Goods   Jan 1920     9.0   EZ  
NCR_Leagles          Services   Feb 1960     7.5   NZ  
Bangalore_Systems    Services   Apr 1950    10.0   SZ  
Chennai_Chemicals       Goods   Aug 1928     2.5   SZ  
Indi_Services        Services   Mar 1920     4.0   NZ  
Bangalore_Breweries     Goods   Oct 1971     2.5   SZ  
Bombay_Finance       Services   Apr 1925    11.0   WZ  
Chennai_Shipping        Goods   Nov 1930     1.0   SZ  
Eastern_Estates         Goods   Jan 1994     5.0   EZ  
Central_Services     Services   Jun 1974     6.0   NZ

In [20]:
def sales(vol_value):
    if vol_value > df.Vol.mean():
        return "Good Sales"
    else:
        return "Average Sales"
df["sales_performance"] = df.Vol.map(sales)
df

Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt     154  Hyd    1    SPRT   
Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL   
Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov   13023  NCR    0    INDI   
Bangalore_Breweries  966  805.00  899    Pvt     119  Blr    1    BREW   
Bombay_Finance       899  917.00  674    Pub    1443  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    Pub     899  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt    1873  Kol    1    EEST   
Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV   

                          GST Start Date  Umrank Zone sales_performance  
Deccan_Sporting      Services   Mar 1943     7.5   SZ     Average Sales  
Kolkata_FMCG            Goods   Jan 1920     9.0   EZ     Average Sales  
NCR_Leagles          Services   Feb 1960     7.5   NZ     Average Sales  
Bangalore_Systems    Services   Apr 1950    10.0   SZ     Average Sales  
Chennai_Chemicals       Goods   Aug 1928     2.5   SZ        Good Sales  
Indi_Services        Services   Mar 1920     4.0   NZ        Good Sales  
Bangalore_Breweries     Goods   Oct 1971     2.5   SZ        Good Sales  
Bombay_Finance       Services   Apr 1925    11.0   WZ     Average Sales  
Chennai_Shipping        Goods   Nov 1930     1.0   SZ        Good Sales  
Eastern_Estates         Goods   Jan 1994     5.0   EZ        Good Sales  
Central_Services     Services   Jun 1974     6.0   NZ     Average Sales

In [22]:
df["sales_performance"] = df.Vol.map(lambda v: "Good Sales" if v > df.Vol.mean() else "Average Sales")
df

Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt     154  Hyd    1    SPRT   
Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL   
Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov   13023  NCR    0    INDI   
Bangalore_Breweries  966  805.00  899    Pvt     119  Blr    1    BREW   
Bombay_Finance       899  917.00  674    Pub    1443  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    Pub     899  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt    1873  Kol    1    EEST   
Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV   

                          GST Start Date  Umrank Zone sales_performance  
Deccan_Sporting      Services   Mar 1943     7.5   SZ     Average Sales  
Kolkata_FMCG            Goods   Jan 1920     9.0   EZ     Average Sales  
NCR_Leagles          Services   Feb 1960     7.5   NZ     Average Sales  
Bangalore_Systems    Services   Apr 1950    10.0   SZ     Average Sales  
Chennai_Chemicals       Goods   Aug 1928     2.5   SZ        Good Sales  
Indi_Services        Services   Mar 1920     4.0   NZ        Good Sales  
Bangalore_Breweries     Goods   Oct 1971     2.5   SZ        Good Sales  
Bombay_Finance       Services   Apr 1925    11.0   WZ     Average Sales  
Chennai_Shipping        Goods   Nov 1930     1.0   SZ        Good Sales  
Eastern_Estates         Goods   Jan 1994     5.0   EZ        Good Sales  
Central_Services     Services   Jun 1974     6.0   NZ     Average Sales

In [27]:

df1 = pd.read_csv("lds_files/lds1.csv")
df2 = pd.read_csv("lds_files/lds0.csv")


In [31]:
fobj = open("output/multi-df.html", "w")

df1.to_html(fobj)
df2.to_html(fobj)

fobj.close()

## Group By

In [32]:
df1

Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt     154  Hyd    1    SPRT   
Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL   
Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov   13023  NCR    0    INDI   
Bangalore_Breweries  966  805.00  899    Pvt     119  Blr    1    BREW   
Bombay_Finance       899  917.00  674    Pub    1443  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    Pub     899  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt    1873  Kol    1    EEST   
Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV   

                          GST Start Date  
Deccan_Sporting      Services   Mar 1943  
Kolkata_FMCG            Goods   Jan 1920  
NCR_Leagles          Services   Feb 1960  
Bangalore_Systems    Services   Apr 1950  
Chennai_Chemicals       Goods   Aug 1928  
Indi_Services        Services   Mar 1920  
Bangalore_Breweries     Goods   Oct 1971  
Bombay_Finance       Services   Apr 1925  
Chennai_Shipping        Goods   Nov 1930  
Eastern_Estates         Goods   Jan 1994  
Central_Services     Services   Jun 1974

In [34]:
dfg = df1.groupby(by="Sector")[]
dfg

In [42]:
df1.groupby(by="Sector")["Rev"].agg(minimum = "min", maximum = "max", diff = (lambda col: col.max() - col.min()))

minimum  maximum   diff
Sector                         
Gov       733.0    881.6  148.6
Pub       821.0    917.0   96.0
Pvt       805.0    839.8   34.8

## Pivot Table

In [43]:
pd.pivot_table(df1, index="Sector")

TypeError: agg function failed [how->mean,dtype->object]

In [44]:
pd.pivot_table(df1, index="Sector", values="Rev", aggfunc="mean")

Rev
Sector            
Gov     812.866667
Pub     867.820000
Pvt     826.343333

In [45]:
pd.pivot_table(df1, index=["Sector", "GST"], values=["Rev", "Vol"], aggfunc=["mean", "min", "max", lambda col: col.max() - col.min() ])

mean                min          max      <lambda>    
                        Rev         Vol    Rev  Vol     Rev  Vol      Rev Vol
Sector GST                                                                   
Gov    Services  812.866667  929.333333  733.0  900  881.60  954   148.60  54
Pub    Goods     852.866667  961.000000  821.0  925  874.40  992    53.40  67
       Services  890.250000  915.000000  863.5  899  917.00  931    53.50  32
Pvt    Goods     819.615000  955.500000  805.0  945  834.23  966    29.23  21
       Services  839.800000  931.000000  839.8  931  839.80  931     0.00   0

In [48]:
diff = lambda col: col.max() - col.min()
diff.__name__ = "Difference"
pd.pivot_table(df1, index=["Sector", "GST"], values=["Rev", "Vol"], aggfunc=["mean", "min", "max",  diff])

mean                min          max      Difference  \
                        Rev         Vol    Rev  Vol     Rev  Vol        Rev   
Sector GST                                                                    
Gov    Services  812.866667  929.333333  733.0  900  881.60  954     148.60   
Pub    Goods     852.866667  961.000000  821.0  925  874.40  992      53.40   
       Services  890.250000  915.000000  863.5  899  917.00  931      53.50   
Pvt    Goods     819.615000  955.500000  805.0  945  834.23  966      29.23   
       Services  839.800000  931.000000  839.8  931  839.80  931       0.00   

                     
                Vol  
Sector GST           
Gov    Services  54  
Pub    Goods     67  
       Services  32  
Pvt    Goods     21  
       Services   0

In [49]:
pd.crosstab(df1.Sector, df1.GST, values=df1.Rev, aggfunc="mean")

GST          Goods    Services
Sector                        
Gov            NaN  812.866667
Pub     852.866667  890.250000
Pvt     819.615000  839.800000

## Dropping of Columns and Rows

In [50]:
df = pd.read_csv("lds_files/lds1.csv")
df

Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt     154  Hyd    1    SPRT   
Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL   
Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov   13023  NCR    0    INDI   
Bangalore_Breweries  966  805.00  899    Pvt     119  Blr    1    BREW   
Bombay_Finance       899  917.00  674    Pub    1443  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    Pub     899  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt    1873  Kol    1    EEST   
Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV   

                          GST Start Date  
Deccan_Sporting      Services   Mar 1943  
Kolkata_FMCG            Goods   Jan 1920  
NCR_Leagles          Services   Feb 1960  
Bangalore_Systems    Services   Apr 1950  
Chennai_Chemicals       Goods   Aug 1928  
Indi_Services        Services   Mar 1920  
Bangalore_Breweries     Goods   Oct 1971  
Bombay_Finance       Services   Apr 1925  
Chennai_Shipping        Goods   Nov 1930  
Eastern_Estates         Goods   Jan 1994  
Central_Services     Services   Jun 1974

In [51]:
df.columns

Index(['Vol', 'Rev', 'Exp', 'Sector', 'EmpCnt', 'HQ', 'MNC', 'StockID', 'GST',
       'Start Date'],
      dtype='object')

In [52]:
df.index

Index(['Deccan_Sporting', 'Kolkata_FMCG', 'NCR_Leagles', 'Bangalore_Systems',
       'Chennai_Chemicals', 'Indi_Services', 'Bangalore_Breweries',
       'Bombay_Finance', 'Chennai_Shipping', 'Eastern_Estates',
       'Central_Services'],
      dtype='object')

In [55]:
df.drop(index=["NCR_Leagles", "Bombay_Finance"], columns=["Vol", "Rev"], inplace=False) # of we make inplace as true the actual data on the dataframe will be deleted

Exp Sector  EmpCnt   HQ  MNC StockID       GST Start Date
Deccan_Sporting      615    Pvt     154  Hyd    1    SPRT  Services   Mar 1943
Kolkata_FMCG         676    Pub    1379  Kol    0    KFMC     Goods   Jan 1920
Bangalore_Systems    650    Gov    1361  Blr    0    BSYS  Services   Apr 1950
Chennai_Chemicals    608    Pub    1656  Che    1    CHEM     Goods   Aug 1928
Indi_Services        609    Gov   13023  NCR    0    INDI  Services   Mar 1920
Bangalore_Breweries  899    Pvt     119  Blr    1    BREW     Goods   Oct 1971
Chennai_Shipping     665    Pub     899  Che    1    SHIP     Goods   Nov 1930
Eastern_Estates      789    Pvt    1873  Kol    1    EEST     Goods   Jan 1994
Central_Services     689    Gov    1573  NCR    1    CSRV  Services   Jun 1974

In [56]:
df

Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt     154  Hyd    1    SPRT   
Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC   
NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL   
Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM   
Indi_Services        954  733.00  609    Gov   13023  NCR    0    INDI   
Bangalore_Breweries  966  805.00  899    Pvt     119  Blr    1    BREW   
Bombay_Finance       899  917.00  674    Pub    1443  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665    Pub     899  Che    1    SHIP   
Eastern_Estates      945  834.23  789    Pvt    1873  Kol    1    EEST   
Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV   

                          GST Start Date  
Deccan_Sporting      Services   Mar 1943  
Kolkata_FMCG            Goods   Jan 1920  
NCR_Leagles          Services   Feb 1960  
Bangalore_Systems    Services   Apr 1950  
Chennai_Chemicals       Goods   Aug 1928  
Indi_Services        Services   Mar 1920  
Bangalore_Breweries     Goods   Oct 1971  
Bombay_Finance       Services   Apr 1925  
Chennai_Shipping        Goods   Nov 1930  
Eastern_Estates         Goods   Jan 1994  
Central_Services     Services   Jun 1974

## Renaming of Labels

In [59]:
df.rename(index={"Indi_Services": "ISR", "Bangalore_Breweries": "Boating Breweries"},columns={"Rev": "Revenue", "Vol": "Volume"}, inplace=False)

Volume  Revenue  Exp Sector  EmpCnt   HQ  MNC StockID  \
Deccan_Sporting       931   839.80  615    Pvt     154  Hyd    1    SPRT   
Kolkata_FMCG          925   874.40  676    Pub    1379  Kol    0    KFMC   
NCR_Leagles           931   863.50  605    Pub    1935  NCR    0    NCRL   
Bangalore_Systems     900   881.60  650    Gov    1361  Blr    0    BSYS   
Chennai_Chemicals     966   863.20  608    Pub    1656  Che    1    CHEM   
ISR                   954   733.00  609    Gov   13023  NCR    0    INDI   
Boating Breweries     966   805.00  899    Pvt     119  Blr    1    BREW   
Bombay_Finance        899   917.00  674    Pub    1443  Mum    0    BFIN   
Chennai_Shipping      992   821.00  665    Pub     899  Che    1    SHIP   
Eastern_Estates       945   834.23  789    Pvt    1873  Kol    1    EEST   
Central_Services      934   824.00  689    Gov    1573  NCR    1    CSRV   

                        GST Start Date  
Deccan_Sporting    Services   Mar 1943  
Kolkata_FMCG          Goods   Jan 1920  
NCR_Leagles        Services   Feb 1960  
Bangalore_Systems  Services   Apr 1950  
Chennai_Chemicals     Goods   Aug 1928  
ISR                Services   Mar 1920  
Boating Breweries     Goods   Oct 1971  
Bombay_Finance     Services   Apr 1925  
Chennai_Shipping      Goods   Nov 1930  
Eastern_Estates       Goods   Jan 1994  
Central_Services   Services   Jun 1974

In [62]:
df.Sector.replace({"Pub": "Public"}, inplace=True)
df

Vol     Rev  Exp  Sector  EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615     Pvt     154  Hyd    1    SPRT   
Kolkata_FMCG         925  874.40  676  Public    1379  Kol    0    KFMC   
NCR_Leagles          931  863.50  605  Public    1935  NCR    0    NCRL   
Bangalore_Systems    900  881.60  650     Gov    1361  Blr    0    BSYS   
Chennai_Chemicals    966  863.20  608  Public    1656  Che    1    CHEM   
Indi_Services        954  733.00  609     Gov   13023  NCR    0    INDI   
Bangalore_Breweries  966  805.00  899     Pvt     119  Blr    1    BREW   
Bombay_Finance       899  917.00  674  Public    1443  Mum    0    BFIN   
Chennai_Shipping     992  821.00  665  Public     899  Che    1    SHIP   
Eastern_Estates      945  834.23  789     Pvt    1873  Kol    1    EEST   
Central_Services     934  824.00  689     Gov    1573  NCR    1    CSRV   

                          GST Start Date  
Deccan_Sporting      Services   Mar 1943  
Kolkata_FMCG            Goods   Jan 1920  
NCR_Leagles          Services   Feb 1960  
Bangalore_Systems    Services   Apr 1950  
Chennai_Chemicals       Goods   Aug 1928  
Indi_Services        Services   Mar 1920  
Bangalore_Breweries     Goods   Oct 1971  
Bombay_Finance       Services   Apr 1925  
Chennai_Shipping        Goods   Nov 1930  
Eastern_Estates         Goods   Jan 1994  
Central_Services     Services   Jun 1974

## Duplicate Hadling

In [64]:
df = pd.read_csv("lds_files/lds33.csv")
df


Date    City  Temperature  Humidity
0  15/1/2019  Shimla           11        67
1  15/2/2019  Shimla           12        65
2  15/3/2019  Shimla           11        57
3  15/1/2019  Shimla           11        67
4  15/1/2019    Pune           29        34
5  15/2/2019    Pune           32        26
6  15/1/2020    Pune           29        21
7  15/1/2019  Mysore           28        49
8  15/2/2019  Mysore           31        47
9  15/1/2020  Mysore           33        49

In [65]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [66]:
df.drop_duplicates(subset=None, keep="first")   # having keep as last will consider the last occurance as original and others will be removed, and vise verca. mean while if we make keep as False will remove all the occurance of dupliucates

Date    City  Temperature  Humidity
0  15/1/2019  Shimla           11        67
1  15/2/2019  Shimla           12        65
2  15/3/2019  Shimla           11        57
4  15/1/2019    Pune           29        34
5  15/2/2019    Pune           32        26
6  15/1/2020    Pune           29        21
7  15/1/2019  Mysore           28        49
8  15/2/2019  Mysore           31        47
9  15/1/2020  Mysore           33        49

In [67]:
df.drop_duplicates(subset=["City", "Temperature"], keep="first")

Date    City  Temperature  Humidity
0  15/1/2019  Shimla           11        67
1  15/2/2019  Shimla           12        65
4  15/1/2019    Pune           29        34
5  15/2/2019    Pune           32        26
7  15/1/2019  Mysore           28        49
8  15/2/2019  Mysore           31        47
9  15/1/2020  Mysore           33        49