### System of Linear Equations

In [2]:
import pyforest

In [3]:
A = np.array([[1,1,1,1], [2, -1, 3, -1], [-1, 4, 1, 2], [3, -1, -1, 4]])
B = np.array([10, 5, 15, 20])

X = np.linalg.solve(A,B)

X

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([1.52173913, 1.08695652, 2.60869565, 4.7826087 ])

Solve the Linear Quations with Sympy Library

In [4]:
import sympy as sp

# Define Symbols
x , y, z , w = sp.symbols('x y z w')

# Define Equations
eq1 = sp.Eq(x+y+z+w, 10)
eq2 = sp.Eq(2*x - y+3*z-w, 5)
eq3 = sp.Eq(-x + 4*y + z+ 2*w, 15)
eq4 = sp.Eq(3*x - y -z + 4*w, 20)

# Solve
solution = sp.solve((eq1, eq2, eq3, eq4), (x, y,z ,w))

# Print
print(solution)

{w: 110/23, x: 35/23, y: 25/23, z: 60/23}


### Eigen Values & Eigen Vectors

In [7]:
A = np.array([[4,6,10], [3,10, 13], [-2, -6, -8]])

eigen_values, eigen_vectors = np.linalg.eig(A)

np.round(eigen_values), eigen_vectors

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(array([4., 2., 0.]),
 array([[ 0.45749571,  0.40824829, -0.57735027],
        [ 0.76249285, -0.81649658, -0.57735027],
        [-0.45749571,  0.40824829,  0.57735027]]))

In [8]:
A = np.array([[13,2,-18], [14,1, -18], [10,2, -15]])

eigen_values, eigen_vectors = np.linalg.eig(A)

np.round(eigen_values), eigen_vectors

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(array([ 3., -3., -1.]),
 array([[-0.63960215,  0.57735027, -0.40824829],
        [-0.63960215,  0.57735027, -0.81649658],
        [-0.42640143,  0.57735027, -0.40824829]]))