## Mathematical Foundation for Data Science
* MathMaster AI Guru - ChatGPT App --> created by the Lecturer Joshi AmrutKumar
#### Types of Representation
1. Linear Algebra
2. Calculus

##### Types of Linear Algebra
1. Vectors (its Operations)


### Vector

1. Numpy Array
2. List
3. Dictionary


#### Numpy Arrays

In [ ]:
import numpy as np

In [2]:
u = np.array([58, 122])
v = np.array([71, 100])
print(u, v)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[ 58 122] [ 71 100]


In [2]:
# Row Vector (4-dimensional vector)
row_vector = np.array([1,2,3,4])

# Column Vector (4-dimensional vector)
col_vector = np.array([[1], [2], [3], [4]])

# Zero Vector (4-dimensional vector)
zero_vector = np.zeros(4)

# Unit Vector (2-dimensional vector)
unit_vector = np.array([1/np.sqrt(2), 1/np.sqrt(2)])

# Vector of 1s (4-dimensional vector)
vector_of_1s = np.ones(4)

# Any Vector object can be represented in N - dimensional way, with N no of attributes representing relation between Vector and attribute 


# Print Vectors
print("Row Vector: ", row_vector)
print("Column Vector: ", col_vector)
print("Zero Vector: ", zero_vector)
print("Unit Vector: ", unit_vector)
print("Vector of 1's: ", vector_of_1s)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Row Vector:  [1 2 3 4]
Column Vector:  [[1]
 [2]
 [3]
 [4]]
Zero Vector:  [0. 0. 0. 0.]
Unit Vector:  [0.70710678 0.70710678]
Vector of 1's:  [1. 1. 1. 1.]


In [4]:
array_data = np.arange(1,10).reshape(3,3)

# Define vectors a, b and c
a = array_data[0]
b = array_data[1]
c = array_data[2]

# Define Scaler k and m
k,m = 2,4

# Verify Commulative Property of Addition: a+b = b+a
print("Commulative Property of Addition:")
print("a + b =", a+b)
print("b + a =", b+a)
print("a+b == b+a :", np.array_equal(a+b, b+a))

# Verify Association Property of Addition: (a+b) + c = a + (b+c)
print("Association Property of Addition:")
print("(a+b) + c : ", (a+b) + c)
print("a + (b+c) : ", a + (b+c))
print("a + (b+c) = a + (b+c) : ", np.array_equal(a + (b+c), (a+b) + c))

<IPython.core.display.Javascript object>

Commulative Property of Addition:
a + b = [5 7 9]
b + a = [5 7 9]


<IPython.core.display.Javascript object>

a+b == b+a : True
Association Property of Addition:
(a+b) + c :  [12 15 18]
a + (b+c) :  [12 15 18]


<IPython.core.display.Javascript object>

a + (b+c) = a + (b+c) :  True


In [5]:
# Norm - Representation of Distance from one vector to other
V = np.array([2,3,4,5])
l2_norm_V = np.sqrt(np.sum(V**2))
l2_norm_V

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

7.3484692283495345

In [6]:
# Define two points P and Q
P = np.array([1, 2])
Q = np.array([4, 6])

# Euclidean Distance
euclidean_dist = np.linalg.norm(P - Q)
print("Euclidean Distance:", euclidean_dist)

# Manhattan Distance (L1 Norm)
manhattan_dist = np.sum(np.abs(P - Q))
print("Manhattan Distance:", manhattan_dist)

# Chebyshev Distance (L-infinity Norm) - chess board distance
chebyshev_dist = np.max(np.abs(P - Q))
print("Chebyshev Distance:", chebyshev_dist)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Euclidean Distance: 5.0


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Manhattan Distance: 7


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Chebyshev Distance: 4


In [7]:
# Define a function to calculate all three norms of a vector
def calculate_norms(vector):
    l1_norm = np.sum(np.abs(vector))
    l2_norm = np.sqrt(np.sum(vector ** 2))
    chebyshev_norm = np.max(np.abs(vector))

    return l1_norm, l2_norm, chebyshev_norm

V = np.array([1,2])
calculate_norms(V)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(3, 2.23606797749979, 2)

In [9]:
# Define a function to calculate all three norms of a vector
def calculate_distances(vector1, vector2):
    vector = vector1 - vector2
    l1_norm = np.sum(np.abs(vector))
    l2_norm = np.sqrt(np.sum(vector ** 2))
    chebyshev_norm = np.max(np.abs(vector))

    return l1_norm, l2_norm, chebyshev_norm

V1 , V2 = np.array([1,2]), np.array([3,4])
calculate_distances(V1, V2)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(4, 2.8284271247461903, 2)

In [13]:
def calculate_distances(vector1, vector2):
    vector = vector1 - vector2
    l2_norm = np.linalg.norm(vector) # by default it gives L2 norm value
    l1_norm = np.linalg.norm(vector, 1)
    chebyshev_norm = np.linalg.norm(vector, np.Inf)

    return l1_norm, l2_norm, chebyshev_norm

V1 , V2 = np.array([1,2]), np.array([3,4])
calculate_distances(V1, V2)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(4.0, 2.8284271247461903, 2.0)

In [14]:
import pandas as pd
from scipy.spatial.distance import cdist
from sklearn.datasets import load_iris

# Iris Data


In [15]:
X, Y = np.array([1,2,3]), np.array([4,5,6])

np.dot(X,Y)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

32

In [16]:
np.dot(Y,X)

<IPython.core.display.Javascript object>

32

In [21]:
def vector_angle(v1,v2):
    theta = np.arccos(np.dot(v1,v2) / (np.linalg.norm(v1)*np.linalg.norm(v2)))

    return np.rad2deg(theta)
vector_angle(X, Y)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

12.933154491899135

In [20]:
vector_angle([1,0], [0,1])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

90.0

In [22]:
def is_orthogonal(x,y):
    return "They are Orthogonal" if np.dot(x,y) == 0 else "Not Orthogonal"
is_orthogonal([1,0,0], [0,1,0])

<IPython.core.display.Javascript object>

'They are Orthogonal'

#### Dot product of two vectors


In [1]:
import pyforest

In [4]:
U = np.array([1,2,3])
V = np.array([4,5,6])
U_dot_V = np.dot(U,V)
norm_U = np.linalg.norm(U)
norm_V = np.linalg.norm(V)

theta = np.arccos(U_dot_V/(norm_U  * norm_V))

print(theta, np.rad2deg(theta))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

0.2257261285527342 12.933154491899135


In [6]:
np.rad2deg(np.arccos(11/(5* np.sqrt(5))))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

10.304846468766044

## Projections of Vectors
### Scaler Projection
<img src="Screenshot 2024-07-20 101207.png" />

In [11]:
scaler_proj_u_on_v = np.dot(U,V) / np.linalg.norm(V) # Scaler Projection of U on V
print(scaler_proj_u_on_v)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

3.6467384467084143


In [12]:
scaler_proj_v_on_u = np.dot(U,V) / np.linalg.norm(U) # Scaler Projection of V on U
print(scaler_proj_v_on_u)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

8.55235974119758


### Vector Projection


In [9]:
# define vector of size 4
X = np.array([1,2,3,4])

xcap = X/np.linalg.norm(X)

print(xcap)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[0.18257419 0.36514837 0.54772256 0.73029674]


In [10]:
np.linalg.norm(xcap) 

<IPython.core.display.Javascript object>

0.9999999999999999

In [13]:
vector_proj_u_on_v = scaler_proj_u_on_v * V / np.linalg.norm(V)
print(vector_proj_u_on_v)

<IPython.core.display.Javascript object>

[1.66233766 2.07792208 2.49350649]


In [14]:
vector_proj_v_on_u = scaler_proj_v_on_u * U / np.linalg.norm(U)
print(vector_proj_v_on_u)

<IPython.core.display.Javascript object>

[2.28571429 4.57142857 6.85714286]
