## Matrices

In [21]:
import pyforest

In [22]:
# 1: Row Matrix 
row_matrix = np.array([1,2,3,4])

# 2. Column Matrix
col_matrix = np.array([[1], [2], [3], [4]])

# 3. Zero Matrix
zero_matrix = np.zeros((3,3))

# 4. Identity Matrix: Diagonal elements are one and all other elements are zero
identity_matrix = np.eye(3)

# 5. Diagonal Matrix: Non-diagonal elements are zero, and other elements are Non-zeros
diag_matrix = np.diag([1,2,3])

row_matrix, col_matrix, zero_matrix, identity_matrix, diag_matrix


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(array([1, 2, 3, 4]),
 array([[1],
        [2],
        [3],
        [4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]]))

In [23]:
# 6. 
square_matrix = np.array([[1,2,3,4],
                          [5,6,7,8],
                          [9,10, 11, 12],
                          [13, 14, 15, 16]])
upper_triangular_matrix = np.triu(square_matrix)

lower_triangular_matrix = np.tril(square_matrix)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

##  Symmetric and Antisymetric matrix


In [24]:
def is_symetric(matrix): # if matrix A is equal to transpose of it then its called as Symmetric Matrix A.T = A
    return np.equal(matrix, matrix.T)

sym_mat = np.array([[1,2,3],
                    [2,4,5],
                    [3,5,6]])

print("Is the Matrix symmetric? :", is_symetric(sym_mat))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Is the Matrix symmetric? : [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [25]:
def is_antisymetric(matrix): # if matrix -A is equal to transpose of it then its called as Antisymmetric Matrix A.T = -A
    return np.equal(-matrix, matrix.T)

sym_mat = np.array([[0,2,3],
                    [-2,0,4],
                    [-3,-4,0]])

print("Is the Matrix Antisymmetric? :", is_antisymetric(sym_mat))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Is the Matrix Antisymmetric? : [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [26]:
np.array([1,2,3]) * np.array([[4], [5], [6]])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

Ways of Multiplying Matrices
* np.dot(A,B)
* A@B
* np.mat_mul(A,B)
* A.dot(B)

Note: do not use the * to multiply the Matrices

In [27]:
np.array([1,2,3]) @ np.array([[4], [5], [6]])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([32])

In [28]:
A, B = np.array([[1,2], [3,4]]), np.array([[4,3], [2,1]])

np.array_equal((A@B).T, B.T@A.T)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

True

In [29]:
B = np.array([[5,6], [7,8]])

# Verify the Determinants det(AB) = det(A) * det(B)


<IPython.core.display.Javascript object>

In [30]:
def matrix_rank(matrix):
    return np.linalg.matrix_rank(matrix)

matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(f"The Rank of the Matrix: {matrix_rank(matrix)}")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

The Rank of the Matrix: 2
