In [11]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

import warnings 
warnings.filterwarnings('ignore')

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "c:\Users\lokesh\anaconda3\python.exe"
  * The NumPy version is: "1.25.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.


ImportError: _multiarray_umath failed to import

ImportError: numpy._core.umath failed to import

In [5]:
# ! pip install PyPDF2 fpdf

In [9]:
! pip install tensorflow

  Using cached tensorflow-2.18.0-cp311-cp311-win_amd64.whl (7.5 kB)
  Using cached tensorflow_intel-2.18.0-cp311-cp311-win_amd64.whl (390.2 MB)
  Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached gast-0.6.0-py3-none-any.whl (21 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached grpcio-1.69.0-cp311-cp311-win_amd64.whl (4.4 MB)
  Using cached tensorboard-2.18.0-py3-none-any.whl (5.5 MB)
  Using cached keras-3.8.0-py3-none-any.whl (1.3 MB)
  Using cached h5py-3.12.1-cp311-cp311-win_amd64.whl (3.0 MB)
  Using cached ml_dtypes-0.4.1-cp311-cp311-win_amd64.whl (126 kB)
  Using cached Markdown-3.7-py3-none-any.whl (106 kB)


## "Hello world" in TF

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

import warnings 
warnings.filterwarnings('ignore')

# Create a Tensor.
hello = tf.constant("hello world")
print(hello)

ModuleNotFoundError: No module named 'tensorflow'

In [11]:
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [13]:
# To access a Tensor value, call numpy().
print(hello.numpy())

b'hello world'


## Data representations in tensors

1. Scalar (0D tensor)

tensor that contain only 1 number is called a scalar tensor.

In [2]:
x=np.array(10)
x

array(10)

In [3]:
x.ndim

0

In [23]:
a = tf.constant(2)


In [24]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=2>

2. Vectors (1D tensor)

An array of numbers id called a vector or 1D tensor. 1D tensor has exactly 1 axis.

A 5D vector has only one axis and has 5 dimensions along its axis whereas, a 5D tensor has 5 axes (and may have any number of entries along each axis.)

In [4]:
x1=np.array([10,13,15])
x1

array([10, 13, 15])

In [5]:
x1.ndim

1

In [28]:
b = tf.constant([2,4])
b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

3. Matrices (2D tensor)

An array of vectors is a matrix or a 2D tensor. A matrix has 2 axes (rows and columns)

In [6]:
x2=np.array([[2,3,4],
             [4,5,6],
             [11,13,7]])
x2

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [11, 13,  7]])

In [30]:
c = tf.constant([[2,3],[4,5]])
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

##Key attributes
1. ndim: number of axes
2. shape: how many dimension the tensor has in each axis
3. datatype (float32, int64, float64 etc.)

In [7]:
x2.ndim

2

In [8]:
x2.shape

(3, 3)

In [16]:
x2.dtype

dtype('int64')

## Manipulating tensors in numpy

#### 1. Create a random tensor with 5 rows and 4 columns. Output random values should form a normal distribution

In [41]:
t1=tf.random.normal([5,4])
t1

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[-0.76205766, -1.4211569 ,  0.53417665, -0.6680408 ],
       [-0.5562921 , -0.4938856 , -0.97492856,  0.7417359 ],
       [-0.06042152, -0.01167426, -0.67512995,  0.22219472],
       [ 0.35617793, -1.1586422 ,  2.1597333 ,  0.3333806 ],
       [-0.05545443,  1.5207409 , -0.4858815 , -0.07932742]],
      dtype=float32)>

#### 2. Access the third row of the above matrix and print its value alone

In [42]:
t1[2,:].numpy()

array([-0.06042152, -0.01167426, -0.67512995,  0.22219472], dtype=float32)

#### 3. Replace all the values of third row to zero

In [43]:
t2=tf.Variable(t1)
t2[2,:].assign(0)

<tf.Variable 'UnreadVariable' shape=(5, 4) dtype=float32, numpy=
array([[-0.76205766, -1.4211569 ,  0.53417665, -0.6680408 ],
       [-0.5562921 , -0.4938856 , -0.97492856,  0.7417359 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.35617793, -1.1586422 ,  2.1597333 ,  0.3333806 ],
       [-0.05545443,  1.5207409 , -0.4858815 , -0.07932742]],
      dtype=float32)>

## Basic tensor operations

1. Element wise operations

Arithmetic Operations Are Element-Wise Operations

In [32]:
a=tf.constant([2,3])
b=tf.constant([4,3])

print(a+b)
print(a*b)

tf.Tensor([6 6], shape=(2,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [33]:
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

# Access tensors value.
print("add =", add.numpy())
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print("div =", div.numpy())

add = [6 6]
sub = [-2  0]
mul = [8 9]
div = [0.5 1. ]


In [ ]:
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

# Access tensors value.
print("mean =", mean.numpy())
print("sum =", sum.numpy())

### Broadcasting
Broadcasting is the concept whose implementation allows us to add scalars to higher dimensional tensors.

eg, what happens with addition if the shapes of the two tensors are different?
the smaller tensor willl be broadcasted to match the shape of the larger tensor.



In [47]:
T1 =tf.constant([[1, 2, 3],      # Rank 2 , shape (2,3)
              [4, 5, 8]])
T2 =tf.constant (20)           # Rank 0 , shape()
#arithmetic operation
T3 =T1+T2
print(T3)

tf.Tensor(
[[21 22 23]
 [24 25 28]], shape=(2, 3), dtype=int32)


In [48]:

# tensor T1
T1 =tf. constant([[[10, 11],   #Rank 3 and shape(2,3,2)
                   [20, 20],
                   [30, 30]],

                 [ [40, 41],
                   [50, 50],
                   [60, 60]   ]])

# tensor T2
T2= tf.constant([[1, 2, 3],    # Rank 2 and shape (2,3)
                 [4, 5, 6]])

#Adding new axis to T2 by .expand_dims() at its trailing end
broadcasted_T2 = tf.expand_dims(T2, axis=-1)

# arithmetic operation
T3=broadcasted_T2+ T1
print(T3)

tf.Tensor(
[[[11 12]
  [22 22]
  [33 33]]

 [[44 45]
  [55 55]
  [66 66]]], shape=(2, 3, 2), dtype=int32)


## Tensor Dot

Dot operation is also called as tensor product, which is the most used operation in neural networks. Its not same as elementwise prosuct (*).

A dot product operation (multiply and sum) is performed on all corresponding dimensions in the tensors, so the operation returns a scalar value

Dot product shape compatibility:
(mxn) . (nxp)=(mxp)

the 2nd dimension of the first matrix should be same with first dimension of   the second matrix.

5. Create 2 random matrices of size [3,3] and [3,3] with minimum value 1 and maximum value 10 and perform element wise multiplication and Matrix Multiplications

In [34]:
a= tf.Variable(np.random.randint(1,11,[3,3]))
b= tf.Variable(np.random.randint(1,11,[3,3]))
print(a)
print(b)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int64, numpy=
array([[4, 3, 8],
       [6, 2, 6],
       [5, 2, 6]])>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=int64, numpy=
array([[ 1,  9, 10],
       [ 8,  4, 10],
       [ 9,  4,  4]])>


In [35]:
a@b

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[100,  80, 102],
       [ 76,  86, 104],
       [ 75,  77,  94]])>

In [37]:
tf.matmul(a,b)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[100,  80, 102],
       [ 76,  86, 104],
       [ 75,  77,  94]])>

## Tensor Reshaping
.
Reshaping a tensor means rearranging its rows and columns to match the output shape

In [54]:
x=tf.constant([[6,1,2],
              [3,4,5]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[6, 1, 2],
       [3, 4, 5]], dtype=int32)>

In [60]:
x1=tf.reshape(x,[3,2])
x1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 1],
       [2, 3],
       [4, 5]], dtype=int32)>

In [12]:
! pip install tensorflow-datasets

                                              0.0/5.3 MB ? eta -:--:--
                                              0.0/5.3 MB ? eta -:--:--
                                              0.0/5.3 MB ? eta -:--:--
                                              0.0/5.3 MB ? eta -:--:--
                                              0.0/5.3 MB 145.2 kB/s eta 0:00:37
                                              0.0/5.3 MB 145.2 kB/s eta 0:00:37
                                              0.0/5.3 MB 131.3 kB/s eta 0:00:41
                                              0.1/5.3 MB 164.1 kB/s eta 0:00:32
                                              0.1/5.3 MB 164.1 kB/s eta 0:00:32
                                              0.1/5.3 MB 163.8 kB/s eta 0:00:32
                                              0.1/5.3 MB 201.8 kB/s eta 0:00:26
                                              0.1/5.3 MB 240.2 kB/s eta 0:00:22
     -                                        0.1/5.3 MB 266.2 kB/s eta 0:00

In [13]:
import tensorflow_datasets.audio.commonvoice as cmv


<module 'tensorflow_datasets.audio.commonvoice' from 'c:\\Users\\lokesh\\anaconda3\\Lib\\site-packages\\tensorflow_datasets\\audio\\commonvoice.py'>
